server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: frontend-service
          uri: http://localhost:8080
          predicates:
            - Path=/
        - id: authorization-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: accounts-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2
        - id: cash-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/cash/**
          filters:
            - StripPrefix=2
        - id: transfer-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=2
        - id: notifications-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.bank.gateway: DEBUG